//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace YazilimSinamaProje.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunSatinAlma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunSatinAlma()
        {
            this.atiks = new HashSet<atik>();
            this.rapors = new HashSet<rapor>();
            this.zimmets = new HashSet<zimmet>();
        }
    
        public int urunID { get; set; }
        public string urunAd { get; set; }
        public Nullable<int> urunAdedi { get; set; }
        public string satinAlinanFirma { get; set; }
        public string urunTipi { get; set; }
        public Nullable<System.DateTime> satinAlmaTarihi { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<decimal> urunToptanFiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atik> atiks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rapor> rapors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zimmet> zimmets { get; set; }
    }
}
